bind = ,156, exec, rog-control-center 
bind = ,211, exec, asusctl profile -n; pkill -SIGRTMIN+8 waybar 
bind = ,121, exec, pamixer -t 
binde = ,122, exec, pamixer -d 5 
binde = ,123, exec, pamixer -i 5 
bind = ,256, exec, pamixer --default-source -t 
binde = ,232, exec, brightnessctl set 5%- 
binde = ,233, exec, brightnessctl set 5%+ 
binde = ,237, exec, brightnessctl -d asus::kbd_backlight set 33%- 
binde = ,238, exec, brightnessctl -d asus::kbd_backlight set 33%+ 
bind = ,210, exec, asusctl led-mode -n 
