gesture = 4, left, dispatcher, workspace, -1
gesture = 4, right, dispatcher, workspace, +1
gesture = 4, down, dispatcher, movetoworkspacesilent, special:minimized
gesture = 4, up, dispatcher, exec, bash /home/vikram_18/.config/hypr/scripts/minimize
gesture = 3, up, dispatcher, fullscreen, 0, set
gesture = 3, down, dispatcher, fullscreen, 0, unset
