source = ~/.config/hypr/keybinds.conf
source = ~/.config/hypr/windowrule.conf
source = ~/.config/hypr/input.conf
source = ~/.config/hypr/style.conf
source = ~/.config/hypr/init.conf
source = ~/.config/hypr/asus-binds.conf
source = ~/.config/hypr/gestures.conf
