exec-once = bash ~/.config/hypr/scripts/xdg-portal-hyprland 
exec-once = dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP 
exec-once = systemctl --user import-environment WAYLAND_DISPLAY XDG_CURRENT_DESKTOP 
exec-once = /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 
exec-once = waybar 
exec-once = blueman-applet 
exec-once = nm-applet --indicator
exec-once = clipse -listen
exec-once = bash ~/.config/hypr/scripts/bgaction 
exec-shutdown = clipse -clear
exec-once = hypr-annotate

env = XCURSOR_THEME,Posy_Cursor
env = XCURSOR_SIZE,24

exec-once = hyprctl setcursor Posy_Cursor 24
