monitor=,preferred,auto,auto,bitdepth,10
monitor=,preferred,auto-right,1,mirror,eDP-1

# monitor = eDP-1, 1920x1080@114.03, 0x0, 1

input {
    kb_layout = us
    kb_variant = ,qwerty
    kb_model =
    kb_options = caps:swapescape
    kb_rules =
    follow_mouse = 1
    touchpad {
        natural_scroll = no
    }
    sensitivity = 0.3
}

device {
    name = epic-mouse-v1
    sensitivity = -0.5
}
