# Opacity settings
windowrule = opacity 0.90 0.90, match:class kitty
windowrule = opacity 0.8 0.8, match:class thunar

# Animations
windowrule = animation popin, match:class kitty
windowrule = animation popin, match:class thunar
windowrule = animation popin, match:class zen 
windowrule = animation slide, match:class wofi

# Move position for specific pop-up
windowrule = move 100%-433 53, match:class wofi 

# Clipboard (Clipse)
windowrule = float on, match:class clipse
windowrule = size 622 652, match:class clipse
windowrule = stay_focused on, match:class clipse
