include ./tokyo.conf

hide_window_decorations yes
placement_strategy top-left

font_family      JetBrains Mono Nerd Font Light
font_size        12
bold_font        JetBrains Mono Nerd Font
italic_font      JetBrains Mono Nerd Font Light Italic
bold_italic_font JetBrains Mono Nerd Font Bold Italic
mouse_hide_wait  2.0
cursor_shape     block
url_color        #0087bd
url_style        dotted
window_margin_width 0
window_padding_width 0
confirm_os_window_close 0
background_opacity 0.80
background_blur 1 
enable_audio_bell no
command_on_bell pw-play /home/vikram_18/.local/share/sounds/freedesktop/stereo/pop-alert.mp3

map ctrl+t new_tab_with_cwd
